/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import codigos.Nodo;
import codigos.listaEnlazada;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;

/**
 *
 * @author j2a0a
 */
public class mainWindow extends javax.swing.JFrame {
    private listaEnlazada lista = new listaEnlazada();
    
    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
    }
    
    public void agregarMiembro(){
        String texto = entryMiembro.getText();
        lista.agregarPrimero(texto);
    }
    
    public void setSizeCombobox() {
        int size = lista.getSize();

        DefaultComboBoxModel<String> aModel = new DefaultComboBoxModel<>();

        for (int i = 0; i < size; i++) {
            aModel.addElement(String.valueOf(i));
        }

        comboBoxIndex.setModel(aModel);
    }
    
    public void addPalabras(int index){
        DefaultComboBoxModel<String> aModel = new DefaultComboBoxModel<>();
        
        aModel.addElement(lista.obtenerMiembro(index));
        palabrasBox.setModel(aModel);
    }
    
    public void eliminarPalabras(int indeX){
        DefaultComboBoxModel<String> aModel = new DefaultComboBoxModel<>();
        
        aModel.addElement(lista.obtenerMiembro(index));
        palabrasBox.setModel(aModel);
    }
    
    public int contarLetras(String texto){
        int contador = 0;
        for (int i = 0; i < texto.length(); i++) {
            contador++;
        }
        return contador;
    }

    public String invertir(String input) {
        char[] caracteres = input.toCharArray();
        int i = 0;
        int j = caracteres.length - 1;

        while (i < j) {
            // Intercambiar caracteres
            char temp = caracteres[i];
            caracteres[i] = caracteres[j];
            caracteres[j] = temp;

            // Mover índices
            i++;
            j--;
        }

        return new String(caracteres);
    }
    
    public String concatenarUltimo(String actualPalabra){
        String ultimo = lista.obtenerMiembro(lista.getSize() - 1);
        
        String actualUltimo = actualPalabra + " " + ultimo;
        
        return actualUltimo;
    }
    
    public static String convertirAMinusculas(String palabra) {
        return palabra.toLowerCase();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        comboBoxIndex = new javax.swing.JComboBox<>();
        operarBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoCantidadLetras = new javax.swing.JTextPane();
        textoInvertido = new javax.swing.JTextPane();
        textoConcatenado = new javax.swing.JTextPane();
        textoMinusculas = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        palabrasBox = new javax.swing.JComboBox<>();
        entryMiembro = new javax.swing.JTextField();
        agregarBoton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        comboBoxIndex.setBackground(new java.awt.Color(236, 255, 252));
        comboBoxIndex.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboBoxIndex.setForeground(new java.awt.Color(0, 102, 102));
        comboBoxIndex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        comboBoxIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxIndexActionPerformed(evt);
            }
        });

        operarBoton.setBackground(new java.awt.Color(236, 255, 252));
        operarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        operarBoton.setForeground(new java.awt.Color(0, 102, 102));
        operarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/checkGreen.png"))); // NOI18N
        operarBoton.setText("Operar");
        operarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        operarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operarBotonActionPerformed(evt);
            }
        });

        eliminarBoton.setBackground(new java.awt.Color(236, 255, 252));
        eliminarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarBoton.setForeground(new java.awt.Color(0, 102, 102));
        eliminarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trashGreen.png"))); // NOI18N
        eliminarBoton.setText("Eliminar");
        eliminarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("1. Número de Letras:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("3. Concatenar con el último miembro:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("4. Pasar a minúsculas");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("2. Invertir frase:");

        textoCantidadLetras.setEditable(false);
        textoCantidadLetras.setBackground(new java.awt.Color(255, 255, 255));
        textoCantidadLetras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        textoInvertido.setEditable(false);
        textoInvertido.setBackground(new java.awt.Color(255, 255, 255));
        textoInvertido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        textoConcatenado.setEditable(false);
        textoConcatenado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        textoMinusculas.setEditable(false);
        textoMinusculas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        jSeparator1.setAlignmentY(1.0F);
        jSeparator1.setAutoscrolls(true);

        palabrasBox.setBackground(new java.awt.Color(236, 255, 252));
        palabrasBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        palabrasBox.setForeground(new java.awt.Color(0, 102, 102));
        palabrasBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));
        palabrasBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabrasBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textoConcatenado, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textoInvertido))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textoCantidadLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textoMinusculas))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboBoxIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(palabrasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(operarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminarBoton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabrasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(textoCantidadLetras))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoInvertido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoConcatenado)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoMinusculas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 800, 480));

        entryMiembro.setForeground(new java.awt.Color(204, 204, 204));
        entryMiembro.setText(" Ingrese una cadena");
        entryMiembro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        entryMiembro.setCaretColor(new java.awt.Color(0, 102, 102));
        entryMiembro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                entryMiembroMousePressed(evt);
            }
        });
        entryMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryMiembroActionPerformed(evt);
            }
        });
        background.add(entryMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 200, 40));

        agregarBoton.setBackground(new java.awt.Color(236, 255, 252));
        agregarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agregarBoton.setForeground(new java.awt.Color(0, 102, 102));
        agregarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plusGreen.png"))); // NOI18N
        agregarBoton.setText("Agregar");
        agregarBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBotonActionPerformed(evt);
            }
        });
        background.add(agregarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 99, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Group 7.png"))); // NOI18N
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryMiembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryMiembroActionPerformed

    private void agregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBotonActionPerformed
        // TODO add your handling code here:
        agregarMiembro();
        setSizeCombobox();
        
        String eleccion = (String) comboBoxIndex.getSelectedItem();
        int indexSeleccionado = Integer.parseInt(eleccion);
        
        addPalabras(indexSeleccionado);
        
        entryMiembro.setText("");
        
        String valorSeleccionado = lista.obtenerMiembro(0);
            textoCantidadLetras.setText(String.valueOf(contarLetras(valorSeleccionado)));

        
        String palabraInvertida = invertir(valorSeleccionado);
        textoInvertido.setText(palabraInvertida);
        
        String palabraConcatenada = concatenarUltimo(valorSeleccionado);
        textoConcatenado.setText(palabraConcatenada);
        
        String palabraMinusculas = convertirAMinusculas(valorSeleccionado);
        textoMinusculas.setText(palabraMinusculas);
    }//GEN-LAST:event_agregarBotonActionPerformed

    private void comboBoxIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxIndexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxIndexActionPerformed

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        // TODO add your handling code here:
        String eleccion = (String) comboBoxIndex.getSelectedItem();
        int indexSeleccionado = Integer.parseInt(eleccion);

        System.out.println(indexSeleccionado + 3);

        if (indexSeleccionado >= 0 && indexSeleccionado < lista.getSize()) {
            lista.eliminarMiembro(indexSeleccionado);
            setSizeCombobox();
        } else {
            System.out.println("Índice seleccionado no válido.");
        }
    }//GEN-LAST:event_eliminarBotonActionPerformed

    private void operarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operarBotonActionPerformed
        // TODO add your handling code here:
        
        try{
            String eleccion = (String) comboBoxIndex.getSelectedItem();
            int indexSeleccionado = Integer.parseInt(eleccion);

            String valorSeleccionado = lista.obtenerMiembro(indexSeleccionado);
            textoCantidadLetras.setText(String.valueOf(contarLetras(valorSeleccionado)));

            String palabraInvertida = invertir(valorSeleccionado);
            textoInvertido.setText(palabraInvertida);

            String palabraConcatenada = concatenarUltimo(valorSeleccionado);
            textoConcatenado.setText(palabraConcatenada);

            String palabraMinusculas = convertirAMinusculas(valorSeleccionado);
            textoMinusculas.setText(palabraMinusculas);
        }
        catch (NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error.", "Error", JOptionPane.ERROR_MESSAGE);

        }
        
    }//GEN-LAST:event_operarBotonActionPerformed

    private void entryMiembroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryMiembroMousePressed
        // TODO add your handling code here:
        entryMiembro.setText("");
    }//GEN-LAST:event_entryMiembroMousePressed

    private void palabrasBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabrasBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palabrasBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBoton;
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> comboBoxIndex;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JTextField entryMiembro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton operarBoton;
    private javax.swing.JComboBox<String> palabrasBox;
    private javax.swing.JTextPane textoCantidadLetras;
    private javax.swing.JTextPane textoConcatenado;
    private javax.swing.JTextPane textoInvertido;
    private javax.swing.JTextPane textoMinusculas;
    // End of variables declaration//GEN-END:variables
}
