/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author j2a0a
 */
public class Operacion4 extends javax.swing.JPanel {
    private JLabel[][] matriz;

    public JLabel[][] getMatriz() {
        return matriz;
    }

    public void setMatriz(JLabel[][] matriz) {
        this.matriz = matriz;
    }
    
    public void showPanel(JPanel panel){
        panel.setSize(1010,350);
        panel.setLocation(0,0);
        
        this.removeAll();
        this.add(panel, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    /**
     * Creates new form Operacion1
     */
    public Operacion4() {
        initComponents();
        
    }
    
    public void llamador(){
        mostrarMayor.setText(String.valueOf(mayor(matriz)));
        mostrarSerie.setText("La serie hasta el numero "+ mayor(matriz) + " es: " +generarFibonacciHasta(mayor(matriz))); 
    }
    
    public static String generarFibonacciHasta(int limite) {
        String fibonacciSeries = "";
        
        int a = 0, b = 1;
        while (a <= limite) {
            fibonacciSeries += a + " ";
            int temp = a + b;
            a = b;
            b = temp;
        
        }
        return fibonacciSeries;
    }
    
    public int mayor(JLabel[][] matriz){
        int mayor = Integer.parseInt(matriz[0][0].getText());
        for (int i = 0; i < matriz.length; i++) {
            for (int j = 0; j < matriz[0].length; j++) {
                if (mayor < Integer.parseInt(matriz[i][j].getText())){
                    mayor = Integer.parseInt(matriz[i][j].getText()); 
                }
            }  
        }
        return mayor;
    }
        
    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarSerie = new javax.swing.JTextPane();
        tituloLabel6 = new javax.swing.JLabel();
        tituloLabel7 = new javax.swing.JLabel();
        tituloLabel8 = new javax.swing.JLabel();
        izquierdaBtn = new javax.swing.JButton();
        mostrarMayor = new javax.swing.JTextPane();

        mostrarSerie.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(mostrarSerie);

        tituloLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloLabel6.setText("4_Serie Fibonacci hasta numero mayor");

        tituloLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloLabel7.setText("Numero mayor: ");

        tituloLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloLabel8.setText("Serie Fibonacci:");

        izquierdaBtn.setText("Izquierda");
        izquierdaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        izquierdaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izquierdaBtnActionPerformed(evt);
            }
        });

        mostrarMayor.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tituloLabel8)
                            .addComponent(tituloLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mostrarMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(izquierdaBtn)
                        .addGap(221, 221, 221)
                        .addComponent(tituloLabel6)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloLabel6)
                    .addComponent(izquierdaBtn))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mostrarMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void izquierdaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierdaBtnActionPerformed
        Operacion3 panel3 = new Operacion3();
        showPanel(panel3);
        panel3.setMatriz(matriz);
        panel3.llamador();
    }//GEN-LAST:event_izquierdaBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton izquierdaBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane mostrarMayor;
    private javax.swing.JTextPane mostrarSerie;
    private javax.swing.JLabel tituloLabel6;
    private javax.swing.JLabel tituloLabel7;
    private javax.swing.JLabel tituloLabel8;
    // End of variables declaration//GEN-END:variables
}
